services:
  - type: web
    name: vaultspring-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: "-Xms512m -Xmx1g"
