services:
  - type: web
    name: vaultspring
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/vaultspring-0.0.12-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
