server:
  port: 8080

spring:
  application:
    name: vaultspring
  profiles:
    default: dev
    group:
      prod-vault:
        - prod
        - vault

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
