server:
  port: 8080

spring:
  profiles:
    active: prod

#spring:
#  security:
#    user:
#      name: user
#      password: senhaSuperSegura123
#      roles: USER
#  application:
#    name: vaultspring
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#    time-zone: America/Bahia
#  web:
#    resources:
#      add-mappings: false
#  datasource:
#    url: ${POSTGRES_URL}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: ${POSTGRES_DRIVER}
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 1
#      connection-timeout: 30000
#      validation-timeout: 3000
#      max-lifetime: 1800000
#      keepaliveTime: 60000
#      idle-timeout: 10000
#      leak-detection-threshold: 15000
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    defer-datasource-initialization: true
#    show-sql: true
