server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: admin
    password: adminpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      validation-timeout: 3000
      max-lifetime: 1800000
      keepaliveTime: 60000
      idle-timeout: 10000
      leak-detection-threshold: 15000
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /tmp/prod-profile.log