server:
  port: 8080

spring:
  flyway:
    enabled: false
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/users_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:adminpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /tmp/vaultspring-dev.log
