CREATE TABLE users (
   user_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   user_name VARCHAR(50) NOT NULL UNIQUE,
   user_password VARCHAR(255) NOT NULL,
   user_email VARCHAR(100) NOT NULL UNIQUE,
   user_created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   user_updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

   CHECK (CHAR_LENGTH(user_name) >= 3),
   CHECK (CHAR_LENGTH(user_password) >= 60)
);
